# Generated by Django 3.1.3 on 2020-11-03 09:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorSchemes',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('base_color', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ropes',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rope_type', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['rope_type'],
            },
        ),
        migrations.CreateModel(
            name='OtherRopes',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('meters_available', models.IntegerField(max_length=15, null=True)),
                ('color_scheme_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ropes.colorschemes')),
                ('rope_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ropes.ropes')),
            ],
        ),
        migrations.CreateModel(
            name='ClimbingRopes',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('meters_available', models.IntegerField(max_length=15, null=True)),
                ('color_scheme_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ropes.colorschemes')),
                ('rope_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ropes.ropes')),
            ],
        ),
    ]
